- name: Launch Database Container
  docker_container:
    name: database
    image: mmorotti/my-database:latest
    networks:
      - name: app-network
    env_file: /opt/.env
    restart_policy: always
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python