- name: Run Front-end Container
  docker_container:
    name: front
    image: mmorotti/my-front:latest
    networks:
      - name: app-network
    restart_policy: always
    state: started
    pull: true
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python