services:
  backend:
    build: ./backend
    networks:
      - ${APP_NETWORK}
      - ${PROXY_NETWORK}
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    restart: on-failure:3

  database:
    build: ./database
    networks:
      - ${APP_NETWORK}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  httpd:
    build: ./httpd
    ports:
      - "80:80"
    networks:
      - ${PROXY_NETWORK}
    depends_on:
      - backend
    restart: no

networks:
  ${APP_NETWORK}: #ne marche pas c'est normal il faut utiliser le generate_compose.ps1
  ${PROXY_NETWORK}:

volumes:
  postgres-data:
